### ISSUE TITLE
Different interpretations of def_conv

### ISSUE THREAD

**Issue by bkvie** [ChunhuanLin/deform_conv_pytorch#10]
Thinking about deformable convolutions, some things I found different interpretations of:
-) Does the offset change for each individual k x k  kernel or is it fixed for the whole image? Would this mean that pixels could potentially overlap? 
-) Is the same offset then applied for each input layer, ie. AxBxC where C might be any number of filters.
-) During inference, keeping the offset generating layers in the network, each k x k kernel would experience an individual offset, or would the offset be the same for the whole image?

**Comment by dingjiansw101** [comment]
The offset change for each individual k x k kernel, you can find the detail in the original paper.

**Comment by bkvie** [comment]
Yes it is, I am just not sure how it is stacked back together:

` index = index.contiguous().unsqueeze(dim=1).expand(-1, c, -1, -1, -1).contiguous().view(b, c, -1)`

will provide an offset, for each kernel, but the kernels position changes throughout the image so the offset is corresponding to which pixels in the input frame x?

**Comment by forrestl111** [comment]
@bkvie Let's denote the centre location of a kernel as (x0, y0) and the offsets of this kernel as (dx_i, dy_i), the index record the location of every elements of the kernel in the feature map, which can be represented as (x_0+dx_i, y_0+dy_i).

**Comment by bkvie** [comment]
so the kernel offset changes for each k x k kernel, also during inference? Is the offset of this kernel as (dx_i, dy_i) somehow restricted?
