### ISSUE TITLE
padded offset 

### ISSUE THREAD

**Issue by bkvie** [ChunhuanLin/deform_conv_pytorch#11]
In code section [https://github.com/ChunhuanLin/deform_conv_pytorch/blob/master/deform_conv.py#L113](url) are you sure multiplying with padded_w is necessary? Doesn't that extend the index beyond x's size?

**Comment by forrestl111** [comment]
Yes, it's necessary. For each location(including the padding locations) of the input x, it will be multiplied by elements for kernels anyway. So we have to make sure offsets are computed in all of the locations of the input x, i.e., [index](https://github.com/ChunhuanLin/deform_conv_pytorch/blob/master/deform_conv.py#L113) has to keep same size with the input x.
