### ISSUE TITLE
ValueError: cannot reshape array of size 18 into shape (1,64,1,1)

### ISSUE THREAD

**Issue by Meimeiainaonao** [ChunhuanLin/deform_conv_pytorch#12]
作者您好，我这篇代码可能看的不是很明白，有些问题想请教一下，希望您能有时间解答，非常感谢。在代码中有self.offsets = nn.Conv2d(128, 18, kernel_size=3, `padding=1)，为什么输入128通道，出来一定是18通道程序才能正常运行呢？我将输出的通道数改成了例如64，就会出现以下问题
                             ValueError: cannot reshape array of size 18 into shape (1,64,1,1)
看了论文，觉得应该和卷积核有关，但是我更改了卷积核保持输出的特征图大小不变，但问题还是一样的~~~所以特别不明白，我非常喜欢您开源的这个代码，很简洁，正在学习。希望您可以帮我解答疑惑。

**Comment by forrestl111** [comment]
你好,输出的通道数是与卷积核的大小相关的.例如,使用3*3的卷积核,那么这个卷积核会有9个参数,那么这9个参数需要18个offset(每个位置有两个方向的offset). 所以如果你要使用3*3卷积核,那么offset输出必须是3*3*2个通道.

**Comment by Meimeiainaonao** [comment]
非常感谢您的解答，我又重新翻看了论文，结合您的代码重新开了一遍，对我的帮助非常大。非常感谢～～

**Comment by forrestl111** [comment]
不客气～
