### ISSUE TITLE
bias for offset and deformable conv

### ISSUE THREAD

**Issue by zhujiagang** [ChunhuanLin/deform_conv_pytorch#5]
Hi, Mr Lin, an excellent work you have done! I have a question after I read many versions of code of deformable cnn, including the officical mxnet version. Why does the offset conv have the bias term like  https://github.com/msracver/Deformable-ConvNets/blob/2b47f673e965701751109db07571ff61d827632d/deeplab/symbols/resnet_v1_101_deeplab_dcn.py#L679 and its after conv doesn't have the bias term https://github.com/msracver/Deformable-ConvNets/blob/2b47f673e965701751109db07571ff61d827632d/deeplab/symbols/resnet_v1_101_deeplab_dcn.py#L683 ?

**Comment by oeway** [comment]
Hi, nice observation. 
It is common to use conv without bias when there is a batchnorm followed after, because batchnorm contains a bias term already.

**Comment by zhujiagang** [comment]
Oh, got it!
