### ISSUE TITLE
Stride setting error in DeformConv2D?

### ISSUE THREAD

**Issue by smilewsw** [ChunhuanLin/deform_conv_pytorch#9]
In the [line](https://github.com/ChunhuanLin/deform_conv_pytorch/blob/master/deform_conv.py#L13) 
`self.conv_kernel = nn.Conv2d(inc, outc, kernel_size=kernel_size, stride=kernel_size, bias=bias)`
why do you set the stride the same as kernel_size? Is it an error?

**Comment by forrestl111** [comment]
No, it's designed to suit the slide window for features extracted from the deformable offsets. You can review  the code [here](https://github.com/ChunhuanLin/deform_conv_pytorch/blob/master/deform_conv.py#L125) to better understand my purpose.
